-- CRIAÇÃO DO BANCO DE DADOS PARA O CENARIO DE E-COMMERCE

CREATE DATABASE ECOMMERCE;
USE ECOMMERCE;

--CRIAR TABELA CLINETE

CREATE TABLE CLIENTE(
        IDCLIENTE NUMERIC(15) AUTO_INCREMENT PRIMARY KEY,
        FNAME VARCHAR(10),
        MINIT CHAR(3),
        LNAME VARCHAR(20),
		CPF CHAR(11) NOT NULL,
		ADDRESS VARCHAR(45),
		CONSTRAINT UNIQUE_CPF_CLIENTE UNIQUE (CPF)
);

--CRIAR TABELA PRODUTO

CREATE TABLE PRODUTO (
       IDPRODUTO NUMERIC(15) AUTO_INCREMENT PRIMARY KEY,
       PNAME VARCHAR(10),
       CLASSIFICATION_KIDS BOOL DEFAULT FALSE,
       CATEGORY ENUM('Eletrônico', 'Vestimenta', 'Brinquedos', 'Alimentos', 'Moveis') NOT NULL,
       AVALIACAO FLOAT DEFAULT 0,
       SIZE VARCHAR(10)
);

CREATE TABLE PAYMENTS(
       IDPAYMENT NUMERIC(15),
	   IDCLIENTE NUMERIC(15),
	   TYPEPAYMENT ENUM('BOLETO', 'CARTÃO', 'DOIS CARTÕES'),
	   LIMITAVAILABLE FLOAT,
	   PRIMARY KEY (IDPAYMENT, IDCLIENTE)
);

--CRIAR TABELA PEDIDO

CREATE TABLE ORDERS(
       IDORDER NUMERIC(15) AUTO_INCREMENT PRIMARY KEY,
	   IDORDERCLIENTE NUMERIC(15),
	   ORDERSTATUS ENUM('Cancelado', 'Confirmado', 'Em Processamento') NOT NULL,
	   ORDERDESCRIPTION VARCHAR(255),
	   SENDVALUE FLOAT DEFAULT 0,
	   PAYMENTCASH BOOL DEFAULT FALSE,
	   IDPAYMENT NUMERIC(15),
	   CONSTRAINT FK_ORDES_CLIENTE FOREIGN KEY(IDORDERCLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);



